apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tektonstores.fuxi.nip.io
spec:
  group: fuxi.nip.io
  names:
    kind: TektonStore
    listKind: TektonStoreList
    plural: tektonstores
    singular: tektonstore
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: TektonStore is the Schema for the tektonstores API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: TektonStoreSpec defines the desired state of TektonStore
            properties:
              author:
                type: string
              data:
                type: string
              forks:
                format: int32
                type: integer
              paramsDescription:
                type: string
              tektonResourceType:
                type: string
            required:
            - author
            - data
            - forks
            - paramsDescription
            - tektonResourceType
            type: object
          status:
            description: TektonStoreStatus defines the observed state of TektonStore
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
